spring.application.name=carrinho-api

spring.jackson.serialization.indent-output=true

# URL de conexão (substitua 'seu_banco' pelo nome do schema criado no MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/carrinho_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true